// <auto-generated />
using System;
using HUCM_App.DbContextfile;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HUCM_App.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HUCM_App.Models.Department", b =>
                {
                    b.Property<int>("DeptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DeptId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CreatedDate")
                        .HasColumnType("text");

                    b.Property<string>("DepartmentName")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedDate")
                        .HasColumnType("text");

                    b.HasKey("DeptId");

                    b.ToTable("Departmentstbl");
                });

            modelBuilder.Entity("HUCM_App.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("CompanyMail")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CreatedDate")
                        .HasColumnType("text");

                    b.Property<DateOnly>("DOJ")
                        .HasColumnType("date");

                    b.Property<int?>("DepartIdDeptId")
                        .HasColumnType("integer");

                    b.Property<string>("EmpUserName")
                        .HasColumnType("text");

                    b.Property<int?>("EmployeeStatus")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("ExitDate")
                        .HasColumnType("date");

                    b.Property<float>("Exp")
                        .HasColumnType("real");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Manager")
                        .HasColumnType("integer");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedDate")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PrimaryContact")
                        .HasColumnType("text");

                    b.Property<string>("PrimaryEmail")
                        .HasColumnType("text");

                    b.Property<int?>("RoleId1")
                        .HasColumnType("integer");

                    b.Property<string>("SecondaryContact")
                        .HasColumnType("text");

                    b.HasKey("EmployeeId");

                    b.HasIndex("DepartIdDeptId");

                    b.HasIndex("RoleId1");

                    b.ToTable("Employeestbl");
                });

            modelBuilder.Entity("HUCM_App.Models.EmployeeJourney", b =>
                {
                    b.Property<string>("CompanyMail")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CreatedDate")
                        .HasColumnType("text");

                    b.Property<DateOnly>("DOJ")
                        .HasColumnType("date");

                    b.Property<int>("DepartId")
                        .HasColumnType("integer");

                    b.Property<string>("EmpUserName")
                        .HasColumnType("text");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<int>("EmployeeStatus")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("ExitDate")
                        .HasColumnType("date");

                    b.Property<float>("Exp")
                        .HasColumnType("real");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Manager")
                        .HasColumnType("integer");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedDate")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PrimaryContact")
                        .HasColumnType("text");

                    b.Property<string>("PrimaryEmail")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<string>("SecondaryContact")
                        .HasColumnType("text");

                    b.ToTable("EmployeeJourneystbl");
                });

            modelBuilder.Entity("HUCM_App.Models.EmpPwd", b =>
                {
                    b.Property<int>("EmpID")
                        .HasColumnType("integer");

                    b.Property<string>("LoginPass")
                        .HasColumnType("text");

                    b.Property<string>("VerifictionCode")
                        .HasColumnType("text");

                    b.ToTable("EmpPwdsTbl");
                });

            modelBuilder.Entity("HUCM_App.Models.EmpRole", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CreatedDate")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedDate")
                        .HasColumnType("text");

                    b.Property<string>("RoleName")
                        .HasColumnType("text");

                    b.HasKey("RoleId");

                    b.ToTable("EmpRolesTbl");
                });

            modelBuilder.Entity("HUCM_App.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProjectId"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CreatedDate")
                        .HasColumnType("text");

                    b.Property<string>("Domain")
                        .HasColumnType("text");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Manager1Id")
                        .HasColumnType("integer");

                    b.Property<int>("Manager2Id")
                        .HasColumnType("integer");

                    b.Property<int>("Manager3Id")
                        .HasColumnType("integer");

                    b.Property<int>("ManagerId")
                        .HasColumnType("integer");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedDate")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("URI")
                        .HasColumnType("text");

                    b.HasKey("ProjectId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("ProjectsTbl");
                });

            modelBuilder.Entity("HUCM_App.Models.Resign", b =>
                {
                    b.Property<int>("ResignId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ResignId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CreatedDate")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("EmpId")
                        .HasColumnType("integer");

                    b.Property<int>("EmpStatus")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedDate")
                        .HasColumnType("text");

                    b.Property<int?>("Reason1ReasonId")
                        .HasColumnType("integer");

                    b.Property<int?>("Reason2ReasonId")
                        .HasColumnType("integer");

                    b.Property<int?>("Reason3ReasonId")
                        .HasColumnType("integer");

                    b.HasKey("ResignId");

                    b.HasIndex("Reason1ReasonId");

                    b.HasIndex("Reason2ReasonId");

                    b.HasIndex("Reason3ReasonId");

                    b.ToTable("ResignsTbl");
                });

            modelBuilder.Entity("HUCM_App.Models.ResignReason", b =>
                {
                    b.Property<int>("ReasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReasonId"));

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.HasKey("ReasonId");

                    b.ToTable("ResignReasonsTbl");
                });

            modelBuilder.Entity("HUCM_App.Models.Skill", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SkillId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CreatedDate")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedDate")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("SkillId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("SkillsTbl");
                });

            modelBuilder.Entity("HUCM_App.Models.TableHandler", b =>
                {
                    b.Property<int>("HandlerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HandlerId"));

                    b.Property<string>("ColName")
                        .HasColumnType("text");

                    b.Property<string>("ColType")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CreatedDate")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedDate")
                        .HasColumnType("text");

                    b.Property<int>("Tableid")
                        .HasColumnType("integer");

                    b.Property<int>("Types")
                        .HasColumnType("integer");

                    b.Property<int>("sequence")
                        .HasColumnType("integer");

                    b.HasKey("HandlerId");

                    b.ToTable("TableHandlersTbl");
                });

            modelBuilder.Entity("HUCM_App.Models.TableHandlerHistory", b =>
                {
                    b.Property<string>("ColName")
                        .HasColumnType("text");

                    b.Property<string>("ColType")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CreatedDate")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<int>("HandlerId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedDate")
                        .HasColumnType("text");

                    b.Property<int>("Tableid")
                        .HasColumnType("integer");

                    b.Property<int>("Types")
                        .HasColumnType("integer");

                    b.Property<int>("sequence")
                        .HasColumnType("integer");

                    b.ToTable("TableHandlerHistoriesTbl");
                });

            modelBuilder.Entity("HUCM_App.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CreatedDate")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedDate")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Usertbl");
                });

            modelBuilder.Entity("HUCM_App.Models.Employee", b =>
                {
                    b.HasOne("HUCM_App.Models.Department", "DepartId")
                        .WithMany()
                        .HasForeignKey("DepartIdDeptId");

                    b.HasOne("HUCM_App.Models.EmpRole", "RoleId")
                        .WithMany()
                        .HasForeignKey("RoleId1");

                    b.Navigation("DepartId");

                    b.Navigation("RoleId");
                });

            modelBuilder.Entity("HUCM_App.Models.Project", b =>
                {
                    b.HasOne("HUCM_App.Models.Employee", null)
                        .WithMany("Projects")
                        .HasForeignKey("EmployeeId");
                });

            modelBuilder.Entity("HUCM_App.Models.Resign", b =>
                {
                    b.HasOne("HUCM_App.Models.ResignReason", "Reason1")
                        .WithMany()
                        .HasForeignKey("Reason1ReasonId");

                    b.HasOne("HUCM_App.Models.ResignReason", "Reason2")
                        .WithMany()
                        .HasForeignKey("Reason2ReasonId");

                    b.HasOne("HUCM_App.Models.ResignReason", "Reason3")
                        .WithMany()
                        .HasForeignKey("Reason3ReasonId");

                    b.Navigation("Reason1");

                    b.Navigation("Reason2");

                    b.Navigation("Reason3");
                });

            modelBuilder.Entity("HUCM_App.Models.Skill", b =>
                {
                    b.HasOne("HUCM_App.Models.Employee", null)
                        .WithMany("Skills")
                        .HasForeignKey("EmployeeId");
                });

            modelBuilder.Entity("HUCM_App.Models.Employee", b =>
                {
                    b.Navigation("Projects");

                    b.Navigation("Skills");
                });
#pragma warning restore 612, 618
        }
    }
}
